### ISSUE TITLE
Db Keys

### ISSUE THREAD

**Issue by muhammedfener** [andreas-mausch/whatsapp-viewer#122]
Is the key found for the crypt12 file not working to decrypt the crypt14 file? Or am I making a mistake somewhere?

**Comment by HeadCrash66** [comment]
My dectyption test also does not work with the actual whatsapp version 2.21.16.6

**Comment by andreas-mausch** [comment]
The key file might change from time to time.
It is important to get the key and the database file at the same time to make sure they match.
