### ISSUE TITLE
error of expected key filesize of 158 bytes does not match

### ISSUE THREAD

**Issue by kumarchetan-1** [andreas-mausch/whatsapp-viewer#123]
on decrypting crypy14 files  expected key filesize of 158 bytes does not match
just see the screenshot attached below
![2021-07-08](https://user-images.githubusercontent.com/78041754/124905726-f54e3880-e003-11eb-9efb-0870a273e26a.png)

**Comment by overth-nker** [comment]
Same message here. 
Crypt14 files, but Whatsapp WA Business.

**Comment by andreas-mausch** [comment]
Only keys with 158 bytes are supported. The latest WhatsApp version (2.21.17.20) produces keys of that size.
