### ISSUE TITLE
Error message "database not found"

### ISSUE THREAD

**Issue by jfbarreto** [andreas-mausch/whatsapp-viewer#13]
Hi,

Whenever I try to open or decrypt a database file I get this "database not found" message. What can I be doing wrong?

Thanks!

**Comment by jfbarreto** [comment]
Any help, please? I need to change my cell phone but I'd really like to store my whatsapp conversations somehow...

**Comment by dickinsc** [comment]
you'll get this error if it can't load either the key file or the message store. Make sure you have both entered into the decrypt dialog box.
If you have the location of the key and messagestore entered I'd take a screen shot but in general it'd be odd for the physical loading of the files to fail unless a wrong value was entered (make sure you use the file picker too, just in case its an issue with the uppercase\lowercase of the path)
