### ISSUE TITLE
If "End-to-end Encrypted Backup" is off, the db files can be read ?

### ISSUE THREAD

**Issue by vic131** [andreas-mausch/whatsapp-viewer#140]
The option _End-to-end Encrypted Backup_ is off on my whatsapp settings, does that means that a key is not necessary to decrypt the db14crypt files ?

**Comment by vb0** [comment]
"End-to-end Encrypted Backup" is a new feature/option - virtually everything you find is from before that (it would be interesting what it does and who knows, maybe with it the users actually could read their own backups but I wouldn't get my hopes up).  

In short yes, you need the key. For iPhones I think there's a way to get everything from a local backup. For Android it's more complex (go figure). One way to do it would be to activate WA on another rooted device (can be an emulator) and restore there a backup with the official way (copy local files or backups via GDrive). Needs two WA activation in total to move the activated WA to the rooted device and back. Another way is https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor , it works actually fairly well and you don't need any extra activation from WA side.  

You might run into either or both of the issues I mentioned below, both solvable:

https://github.com/andreas-mausch/whatsapp-viewer/issues/142
https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/issues/82  

You might want to close this issue as getting the key isn't an issue for this project, let's try to keep it as low maintenance as possible.
