### ISSUE TITLE
problem decrypting database with key in case my android is rootless

### ISSUE THREAD

**Issue by BrunoHenrique229** [andreas-mausch/whatsapp-viewer#144]
Hi Andreas, how are you? I used a program to extract a whatsapp key without root, the process went well but when I go to decrypt the database with the key it returns this error saying that the key is not valid link of program https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor
![ola](https://user-images.githubusercontent.com/44625772/156782527-471e4e94-3c12-455f-9fab-4bfdc5058e54.PNG)

**Comment by afeoli** [comment]
@BrunoHenrique229 Were you able to solve this?
