### ISSUE TITLE
Could not decrypt block / Decrytion failed. Error during unzipping (inflate)

### ISSUE THREAD

**Issue by WACRYP** [andreas-mausch/whatsapp-viewer#15]
Hi, since a few days (after some kind of mini upgrade of whats app, I'm getting the error "Decryption failed. Error during unzipping (inflate)"
If I try it again the same error is gone and replaced by the error "could not decrypt block" when I try to decrypt a crytp8 db.

The key I have extracted is exactly the same as before...

When I extract the key with WhatsApp KeyExtract, the replaced version of WhatsApp has to be upgrdaded after extract.

Do I need an update?!

**Comment by andreas-mausch** [comment]
https://github.com/andreas-mausch/whatsapp-viewer/issues/11
Can you please try the updated version?

**Comment by amilmac** [comment]
Hi Andreas, i was using older version of WhatsApp Viewer with my phone key and crypt7 files with no problems. Now i need to work againt and downloaded the latest version and tried crypt8 files with the same key (same phone) and im having the same error messege of WACRYPT. Do i need to "re extract" the key with WhatsAppKeyExtract ?. Hints?. Tnks in advance.

**Comment by andreas-mausch** [comment]
Yes you will need to re-extract the key.
