### ISSUE TITLE
Whatsapp-viewer should include a License and it should be the GNU GPL

### ISSUE THREAD

**Issue by Dragnucs** [andreas-mausch/whatsapp-viewer#16]
Whatsapp-viewer makes use of the the [AES](https://tls.mbed.org/aes-source-code) library which is released under the GNU GPLv2+. So long story short; Whatsapp-viewer needs to be GPL too. Not including any license means you do not comply with GPL.

**Comment by andreas-mausch** [comment]
The license of the AES library now used in WhatsApp Viewer is Apache 2, which is non-infectious.
I will add a LICENSE file, though.

**Comment by iw0fzw** [comment]
I don't think you can change the terms of license one time adopted it! The solution is to go to the fork and to do a new software. If you adopted the GNU LGPL V2 you can't revoke it you must continue till that software has not finished its own normal circle of life.

**Comment by iw0fzw** [comment]
Then you haven't any idea about terms of license read: https://www.gnu.org/licenses/license-list.html#SoftwareLicenses the Apache License. Version 2.0  http://directory.fsf.org/wiki/License:Apache2.0 is GNU GENERAL PUBLIC LICENSE compatible with the Version 3 of GNU GENERAL PUBLIC LICENSE.  https://www.gnu.org/licenses/gpl-3.0.txt AND IS INCOMPATIBLE with the GNU GENERAL PUBLIC LICENSE VERSION 2   https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt YOU HAVE NOT SOLVED NOTHING!

**Comment by andreas-mausch** [comment]
I'd prefer if you don't shout at me, sir.

With the previously used version of the AES lib under GPLv2 I had conflicting licenses in the project, as you have pointed out. At this point in time WhatsApp Viewer had no LICENSE at all (and still has none). And it couldn't even be GPLv2 or Apache or MIT, because of the incompatibilities.

I went ahead and resolved the conflicting licenses by updating to a newer version of the AES lib. Apparently they were able to change their license. 

Now as there currently is no GPLv2 lib in this project I don't see how I cannot chose MIT or Apache as my license.

**Comment by Dragnucs** [comment]
@andreas-mausch GPL is a very good license. Why do you hesitate to use it? You only need to use the right version.

**Comment by andreas-mausch** [comment]
@Dragnucs as stated above I dislike infectious licenses. I've added a file for MIT.

**Comment by Dragnucs** [comment]
GPL is said to e copyleft not infectious. Being copyleft is a a positive quality for a licence.

**Comment by andreas-mausch** [comment]
Why?

**Comment by Dragnucs** [comment]
Because:
>  The simplest way to make a program free software is to put it in the public domain, uncopyrighted. This allows people to share the program and their improvements, if they are so minded. But it also allows uncooperative people to convert the program into proprietary software. They can make changes, many or few, and distribute the result as a proprietary product. People who receive the program in that modified form do not have the freedom that the original author gave them; the middleman has stripped it away.
> [...]
>  Copyleft guarantees that every user has freedom.

[(source)](https://www.gnu.org/copyleft/)
