### ISSUE TITLE
Provide Windows Phone support

### ISSUE THREAD

**Issue by mustafaiman** [andreas-mausch/whatsapp-viewer#17]
There is no tool to extract windows phone whatsapp backups. I do not know how much effort this require. That would be fantastic if you see how much effort it takes to port your program and consider doing it.

**Comment by andreas-mausch** [comment]
I don't own a Windows Phone so even if someone provided me test files I would have a hard time to  maintain it. So currently Windows Phone support is not planned, sorry.
