### ISSUE TITLE
Can't decrypt DB on Whatsapp 2.12.300

### ISSUE THREAD

**Issue by Mirlin89** [andreas-mausch/whatsapp-viewer#19]
Hi Andreas!
New update, "new" issue!
With the WA updated version (5 october), the error "Decryption failed. Error during unzipping (inflate)." is back!
Can you take a look on this? 
Many thanks for your work!

**Comment by npulidomonroy** [comment]
Same issue here :-(

**Comment by andreas-mausch** [comment]
Most likely you have the wrong key.
#11
