### ISSUE TITLE
A new crypted database has been released (db.crypt9). We need Support please.

### ISSUE THREAD

**Issue by DMarcus115** [andreas-mausch/whatsapp-viewer#27]
This month a new crypted database (db.crypt9) has been finally release. A new version of Whatsapp Viewer is necessary :=) . We would appreciate your valuable help. Thanks.

**Comment by tguser** [comment]
I confirm crypt9 been in beta for some weeks and now it is in official play store download (updated yesterday).
Any news about a working / in work update for wa-viewer?

**Comment by lorenmain** [comment]
New database ( db.crypt9 ) .
Will it be possible to have viewer for it ?.
Thank you

**Comment by k-crip** [comment]
Andreas Mausch, you are our hope!
Is it possible to have crypt9 decrypted?
Would you try to reach that goal?
Thanks in advance

**Comment by andreas-mausch** [comment]
Hi there,

just wanted to say I am aware of this issue and work on it if you give me some spare time. :)
However, I haven't done the decryption of crypt8 by myself but used known methods from XDA.

Andreas

**Comment by k-crip** [comment]
Thank you very much Andreas.
I really admire your intelligence and support.
Hope you perform well with decryption.
I will be aware of your progress.
Kind regards.

**Comment by lorenmain** [comment]
Thank you very much for your patience with conosotros .
Of course also thanks to all employees of XDA for everything you do .

**Comment by thiagozmed** [comment]
Any idea off crypt9 decryption to work?

**Comment by Raffaa** [comment]
They are already "testing" crypt10 in the beta builds

**Comment by DMarcus115** [comment]
Dear Andreas and dear friends of github in the next page you will find a way to decrypt the database 9, 10 and 11.  I have used it and it works correctly. The program generates a decrypted file which can be read using the classic whatsapp viewer. I hope you find it useful. My best wishes to all. 

http://whatcrypt.com/

Regards.

**Comment by thiagozmed** [comment]
@DMarcus115 it takes a long long time to decrypt?

**Comment by DMarcus115** [comment]
Not, the process is simple. You upload the key file and then the encrypted file. In a few seconds the  download of decrypted file starts. The process is very fast.

**Comment by klawdhfzasjhaa** [comment]
+1 for the crypt9 update. :)

**Comment by thiagozmed** [comment]
Thanks, crypt9 worked for me

**Comment by AcidBurns** [comment]
Well nice for the whatcrypt update, but i'd rather not upload my database with key to some website. please give the technical details to andreas as he also asked in the forum :D

**Comment by cyberdecker** [comment]
Thanks for the tip of whatcrypt, but it is normal for the decrypt to take too much time? For me is taking a long time...

**Comment by AcidBurns** [comment]
yes, the service deals with a high load. but please do not use this. not just for your own sake but also for your contacts sake. not only all the textmessages and thumbnails of pictures you send are in the database but also all telephone numbers of people you communicate with.
since I don't see any statement of how the service is paid I suspect that you data may be abused. Keep in mind: you're uploading ALL your chats to that server together with a key to decrypt them.

**Comment by cyberwinder** [comment]
@AcidBurns 

Or you could just download the free app: [http://whatcrypt.com/com.whatcrypt.apk] ?!?!?

**Comment by andreas-mausch** [comment]
See #26, WhatsApp Viewer won't support crypt9.
