### ISSUE TITLE
problem to decrypt the whatsapp mesasages of extension .crypt10

### ISSUE THREAD

**Issue by alihusainnaqvi110** [andreas-mausch/whatsapp-viewer#29]
I am having a problem related  to the whatsapp decryption messages of the latest extension .crypt10. I really appreciate your help. 
Thanks in advance... :=)

**Comment by cyberwinder** [comment]
This has already been discussed concerning crypt9. The latest crypt file in the beta builds is crypt12. A workaround would be to download http://whatcrypt.com/com.whatcrypt.apk and decrypt your database with that. Then you can open the db file in whatsapp viewer.

**Comment by sebastialonso** [comment]
To be able to use that tool you need to have your phone rooted though :/
Otherwise, you can't fetch your crypt key

**Comment by andreas-mausch** [comment]
See #26, #27. Same here: WhatsApp Viewer won't support crypt10.
