### ISSUE TITLE
Supporting crypt12

### ISSUE THREAD

**Issue by EliteAndroidApps** [andreas-mausch/whatsapp-viewer#31]
Not an issue but a solution (feel free to port the code).

See: [WhatsApp Crypt12 Database Decrypter](https://github.com/EliteAndroidApps/WhatsApp-Crypt12-Decrypter)

Users can run this script to decrypt their crypt12 files prior to opening them with WhatsApp Viewer :+1:

**Comment by andreas-mausch** [comment]
Tyvm, thanks for letting me know.

**Comment by EliteAndroidApps** [comment]
You're welcome. Just added Java source too.

**Comment by andreas-mausch** [comment]
Implemented in v1.9
