### ISSUE TITLE
can't export my chat

### ISSUE THREAD

**Issue by joschi7** [andreas-mausch/whatsapp-viewer#32]
Hi 

I see my chats and it works as far as I can see with smaller ones but I have a big chat I wanted to export but when I tap the export button nothing happens... Idk what to do and I got the viewer only to export that chat that is bigger than 10k messages.

I hope you can help me 

Thank you, joschi

**Comment by andreas-mausch** [comment]
Uh. Can you send me the msgstore.db? I'd take a look then. I can understand if you don't want to share it but then it's hard for me to fix it.

**Comment by joschi7** [comment]
Ok, gonna send you a private email

thank you

**Comment by andreas-mausch** [comment]
Some send-file-service. I don't really know a good one, but you can try this one maybe: https://transfer.pcloud.com

**Comment by joschi7** [comment]
Ok, done. 

password: Aloha7..8

**Comment by andreas-mausch** [comment]
Got it, will take a look at it when I'm home. I need to setup the development environment first, though. I don't have Visual Studio installed right now.

**Comment by joschi7** [comment]
ok, thx

**Comment by joschi7** [comment]
Do you already got an idea what could be wrong?

**Comment by andreas-mausch** [comment]
Export worked on my PC, can't really tell what's wrong. I've send you the exported conversation via email and deleted the database file from my hard drive.

**Comment by joschi7** [comment]
Hey Andreas

 

Is there a possibility to export the chat from the original (Unicode UTF8) Whatsapp code? I need the .txt file of the chat in the same form/code as it would be exported directly from Whatsapp per Mail.

 

thx joël

 

Gesendet: Sonntag, 26. Februar 2017 um 21:50 Uhr
Von: "Andreas Mausch" <notifications@github.com>
An: andreas-mausch/whatsapp-viewer <whatsapp-viewer@noreply.github.com>
Cc: joschi7 <jodelmail@gmx.ch>, Author <author@noreply.github.com>
Betreff: Re: [andreas-mausch/whatsapp-viewer] can't export my chat (#32)


Export worked on my PC, can't really tell what's wrong. I've send you the exported conversation via email and deleted the database file from my hard drive.
