### ISSUE TITLE
Question regard bruteforce

### ISSUE THREAD

**Issue by BernardoLima** [andreas-mausch/whatsapp-viewer#35]
Would you be able to speculate if bruteforcing crypt12 key would take more than years to a regular machine?

**Comment by andreas-mausch** [comment]
It will take more than years. crypt12 is encrypted with AES 256-bit GCM

**Comment by infohash** [comment]
Is this AES 256-bit GCM key sent by WhatsApp server to the client or is it generated by the client itself by deriving it from some secret sent by WhatsApp server after OTP verification?
