### ISSUE TITLE
batch export

### ISSUE THREAD

**Issue by raynert** [andreas-mausch/whatsapp-viewer#36]
Would be great if you could make a bulk export option, rather than exporting individual chats. 
Also, export for chats with a / forward slash character in them doesn't work.

**Comment by miki2999** [comment]
Hello
I also want to export everything in one click to TXT

**Comment by willnode** [comment]
Just for future reference,

I found a fork that already does this:

https://github.com/LambdaSoft/whatsapp-viewer/releases/tag/v1.12.1
