### ISSUE TITLE
crypt12 - Error during unzipping (inflate)

### ISSUE THREAD

**Issue by madknownz** [andreas-mausch/whatsapp-viewer#37]
Please help, tried several time but the same result error with unzipping (inflate). Need to view and old important data from my backup. 
v1.9

**Comment by utmuk** [comment]
I also have this issue. Most of the files are decoded successfully using crypt key. But some lead to this error:

Error
---------------------------
Decryption failed. Error during unzipping (inflate).

And I know for sure the files are not broken. They are all from the same device, made in the same period. A while ago, when there was the same issue with crypt8 file, the author gave some openssl commands to try to decode the files manually. Could you please give us such a command for crypt12 files?

**Comment by izzylaif** [comment]
The error is misleading.
This is because your key is incorrect. Everytime Whatsapp verifies your phone number, a new key is generated.
Just open a couple crypt12 files that decodes fine in a text/hex editor and visually compare the beginning of the file to a couple of crypt12 that don't decode with the same key. You see that for the OK files the the beginnings of the files are identical, and different from those that don't open, which are also identical among themselves.
The utility applies the key, but since it's incorrect, the resulting garbage is not an archive and cannot be inflated, thus the error.
What you may try to do is:
- copy to pc and rename one of those files to msgstore.db.crypt12
- uninstall whatsapp from the phone
- install it again BUT DO NOT RUN IT YET
- copy back the renamed file to the whatsapp folder
- run the app, confirm the phone number, and agree to restore the database.
Whatsapp might send one of the old keys to your phone to decode the backup

Please let me know if it works.

**Comment by andreas-mausch** [comment]
I try to provide you some terminal commands by tomorrow.
Thank you izzylaif for the detailed description. :+1:

**Comment by utmuk** [comment]
**izzylaif**
I have quite a bunch of files and I checked all of them. Here are the results:

msgstore-2017-03-25.1.db.crypt12 - OK
msgstore-2017-03-26.1.db.crypt12 - OK
msgstore-2017-03-27.1.db.crypt12 - OK
msgstore-2017-03-28.1.db.crypt12 - OK
msgstore-2017-03-29.1.db.crypt12 - OK
msgstore-2017-03-30.1.db.crypt12 - OK
msgstore-2017-03-31.1.db.crypt12 - OK
msgstore-2017-04-01.1.db.crypt12 - OK
msgstore-2017-04-02.1.db.crypt12 - OK
msgstore-2017-04-03.1.db.crypt12 - OK
msgstore-2017-04-04.1.db.crypt12 - OK
msgstore-2017-04-05.1.db.crypt12 - OK
msgstore-2017-04-06.1.db.crypt12 - OK
msgstore-2017-04-07.1.db.crypt12 - OK
msgstore-2017-04-08.1.db.crypt12 - OK
msgstore-2017-04-09.1.db.crypt12 - Error
msgstore-2017-04-10.1.db.crypt12 - OK
msgstore-2017-04-11.1.db.crypt12 - Error
msgstore-2017-04-14.1.db.crypt12 - OK
msgstore-2017-04-15.1.db.crypt12 - OK
msgstore-2017-04-16.1.db.crypt12 - OK
msgstore-2017-04-17.1.db.crypt12 - Error
msgstore-2017-04-18.1.db.crypt12 - Error
msgstore-2017-04-19.1.db.crypt12 - OK
msgstore-2017-04-20.1.db.crypt12 - OK
msgstore-2017-04-21.1.db.crypt12 - OK
msgstore-2017-04-22.1.db.crypt12 - OK
msgstore-2017-04-23.1.db.crypt12 - OK
msgstore-2017-04-24.1.db.crypt12 - OK
msgstore-2017-04-25.1.db.crypt12 - OK
msgstore-2017-04-26.1.db.crypt12 - OK
msgstore-2017-04-27.1.db.crypt12 - OK
msgstore-2017-04-28.1.db.crypt12 - OK
msgstore-2017-04-29.1.db.crypt12 - OK
msgstore-2017-04-30.1.db.crypt12 - Error
msgstore-2017-05-01.1.db.crypt12 - OK
msgstore-2017-05-02.1.db.crypt12 - OK
msgstore-2017-05-03.1.db.crypt12 - OK
msgstore-2017-05-04.1.db.crypt12 - OK
msgstore-2017-05-05.1.db.crypt12 - OK
msgstore-2017-05-06.1.db.crypt12 - OK
msgstore-2017-05-07.1.db.crypt12 - OK
msgstore-2017-05-08.1.db.crypt12 - OK

If you look at them, you will see that your theory about different key is wrong. Also here is the comparison of two "OK" files:
<img width="241" alt="001" src="https://cloud.githubusercontent.com/assets/28525658/25862010/39d88fd8-34ef-11e7-995c-856e5117b6e4.PNG">
And comparison of one "OK" and one "Error" file:
<img width="250" alt="002" src="https://cloud.githubusercontent.com/assets/28525658/25862024/4a8f9e5c-34ef-11e7-9f8c-32c30177317a.PNG">
Here again we see that the key in all files is the same. So all in all it is not a problem with the key file

**Comment by andreas-mausch** [comment]
Can you please try this script and let me know if it works for all of your files (I hope you are familar with node)? If it does there must be a bug in the C++ code.

https://github.com/andreas-mausch/whatsapp-viewer/blob/node/decrypt-crypt12.js

```
$ node ./decrypt-crypt12.js ./msgstore.db.crypt12 ./key ./msgstore.db
Key:  <Buffer XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX>
Initialization vector:  <Buffer XX XX XX XX XX XX XX XX XX XX XX XX>
crypted:  <Buffer XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX ... >
decrypted (gzipped):  <Buffer XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX ... >
decrypted:  <Buffer XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX ... >

written to msgstore.db
```

OpenSSL doesn't support AES GCM on command line for some reason:
```
$ openssl enc -aes-256-gcm
AEAD ciphers not supported by the enc utility
```

**Comment by any81** [comment]
Good morning Andreas

**Comment by any81** [comment]
I want to  tell you thanks very much ,I see that every day you trying to
help me....
The problem it's that I Brock my PC and I can use only tablet:(end I want
to ask you from all my heart to start from zero  because I have on my mind
every day ..Maybe  you understand me ,I want to finish because it's  more
than 2year's he lie on me ...and if you want I have her number and his.
If you need money I give you but I don't have much:( But if one day you
want to come to Italy I will take you to Venice and the house of Romeo&
Giulieta.thanks

**Comment by utmuk** [comment]
**andreas-mausch**
Unfortunately I am not even familiar with linux. But I downloaded a virtual machine image of Ubuntu and tried the command you told. First I had to install the package "node-js", then I entered the command you told me, and it seems something is missing:
<img width="339" alt="1" src="https://cloud.githubusercontent.com/assets/28525658/25989417/b75d7a24-3704-11e7-8fe9-f770abf3096b.PNG">

**Comment by utmuk** [comment]
I installed npm and tried 
npm install node-aes-gcm
but it ended with some "failed to fetch" errors.

**Comment by any81** [comment]
Ok np thanx again .I let you my phone number 00393482944623 if you like we
can talk sometime ....nice to meet you Andreas my name it's Mariana.

**Comment by utmuk** [comment]
OK, after a long process of googling and fighting with one error after another I at last managed to install the tools and here is what I came up with:
![clipboard02](https://cloud.githubusercontent.com/assets/28525658/25991203/274d2cc0-370b-11e7-98f3-8d5a450b931b.png)
The encrypted database I used is the "OK" file

**Comment by any81** [comment]
I have t do something me ?

**Comment by any81** [comment]
I mean it's not possible to open this ...?

**Comment by utmuk** [comment]
**any81**
No, my friend, sorry. I have been talking to the author of the program all this time. Maybe you should start another topic?

**Comment by any81** [comment]
You have any idea?sorry if I disturbing you :(

**Comment by andreas-mausch** [comment]
Hi,

@any81 Thanks for the invitation to Italy, I appreciate that. Were you aware your comments are visible in public? I've removed the phone number from your comment. We discuss on this page: https://github.com/andreas-mausch/whatsapp-viewer/issues/37
For private messages you can contact me at andreas.mausch@gmail.com

@utmuk Good job on coming so far if linux and node are new to you. Most people would've given up already. In your last screnshot the parameters are not correct, please check them precisely:
```
node ./decrypt-crypt12.js ./msgstore.db.crypt12 ./key ./msgstore.db
```
If you know python, this script might be easier to use for you: https://github.com/EliteAndroidApps/WhatsApp-Crypt12-Decrypter

Andreas

**Comment by any81** [comment]
By email ,what its 37?:)

**Comment by any81** [comment]
I let  you my number to dany.....

**Comment by any81** [comment]
I will make spaghetti ,please come eat whit me ,you like?

On May 12, 2017 10:55 AM, "Dany Corkova" <danycorkova@gmail.com> wrote:

I let  you my number to dany.....

**Comment by any81** [comment]
When you can you want please send to me phyton right link  because I don't
have idea which it more good....thanx

**Comment by utmuk** [comment]
Yes, I was more successful with Python
<img width="303" alt="command" src="https://cloud.githubusercontent.com/assets/28525658/25995053/2370268a-3719-11e7-8d1c-b28226a6f630.PNG">
The screenshot is self-explanatory. Python script decodes successfully even if the latest version of WhatsApp Viewer showed the error "Decryption failed. Error during unzipping (inflate)."

**Comment by utmuk** [comment]
And I checked the Error.db. It is good.

**Comment by any81** [comment]
My God are you machine ,robot or what ?:)my God you are so clever...can I
ask you how old are you ?I non but reali you are number 1000 I make you my
compliments....

**Comment by utmuk** [comment]
You may show you gratitude to the author by stopping to flood the topic

**Comment by utmuk** [comment]
**andreas-mausch**
I used a batch script to decode all files
for /r %%i in (*.crypt12) do python decrypt12.py key %%i %%i.db
All files were decoded OK except two. But those two were decoded OK by Whatsapp Viewer

**Comment by utmuk** [comment]
nope, those two files most probably are REALLY damaged. Because those database create by Whatsapp Viewer can't be opened in database viewer

**Comment by any81** [comment]
I try to open but ask me password...:( you sei that you decrypt the file ?
Where are ?

**Comment by any81** [comment]
Np for 2file ...awww believe me I will don forget you never in my
life...And this because I am very good whit big heart but I dont accept to
anyone to play whit me...are you live in Germani?

On May 12, 2017 12:33 PM, "Dany Corkova" <danycorkova@gmail.com> wrote:

I try to open but ask me password...:( you sei that you decrypt the file ?
Where are ?

**Comment by any81** [comment]
I go max 10 minute out and I will( brb)

**Comment by any81** [comment]
I am back ,you do something?

**Comment by any81** [comment]
Hiii can you tell me the last step please? Sorry becouse I disturbing you
...

**Comment by andreas-mausch** [comment]
@utmuk Ok then it is a bug in WhatsApp Viewer. :( Could you provide me one failing database file plus the key, so I'd be able to debug it?
I will delete the files immediately after I finish the work.

@any81 Please, utmuk is absolutely right. You are hijacking and spamming this thread and make it hard for us to solve a bug in the app. He is putting in a lot of effort to narrow the bug down so please either create a new issue or use my contact details above to reach me. Don't reply to this email please.

**Comment by utmuk** [comment]
**andreas-mausch**
Sorry, I can't send you the files, because they have been trusted to me by someone else and are confidential. But I can do any kinds of tests and send you logs and results if you want.

**Comment by carlostang** [comment]
Hi Andreas, i have the same error decrypting: Error during unzipping (inflate) , is there a new version with the fix for that error?  I can only decrypt a single file.

**Comment by zecaguilherme** [comment]
@andreas-mausch I have the exactly same problem. Most of the files are decrypted correctly but some aren't.

**Comment by andreas-mausch** [comment]
@zecaguilherme Could you provide me sample files? Would help a lot.

**Comment by zecaguilherme** [comment]
@andreas-mausch Sorry taking so long to reply.... Yeah, I can provide. Just tell me how to send you the files

**Comment by andreas-mausch** [comment]
@zecaguilherme andreas.mausch@gmail.com
if it is too big use https://uploadfiles.io/
thank you

**Comment by virginia91** [comment]
Hi, Andreas.
I have tried to decrypt a whatsapp database (crypt12) from my old mobile phone and I get the error "Error during unzipping (inflate)".

What happened is that I stopped using my old phone and the phone company cancelled the number. Then, one day, I decided to recover my conversations to save them on the computer. I switched on the telephone and a message appeared telling me that I had to verify my phone number for Whatsapp (the number did not belong to me anymore). I became nervous and I verified a new phone number.

I am afraid that verifying Whatsapp with another number might have damaged the databases or the key.

I would be very grateful if you could help me or tell me if there is any solution.

Thank you in advance for your time and for your generosity.

I have sent you an email with the files :)

Kind regards

**Comment by Ruud79** [comment]
Hi Andreas, i have the same error decrypting: Error during unzipping (inflate). Mostly it works but sometimes not, then the next backup or the next therafter will work again. I can supply you with sample files if you need more than @zecaguilherme already provided.

**Comment by andreas-mausch** [comment]
Thanks @Ruud79, I haven't found time yet to fix this. However, I've set up a development VM for WhatsApp Viewer so I should be able to fix it fast. I'll let you know if I need more files.

**Comment by andreas-mausch** [comment]
Will be solved in v1.10
Thank you very much for the provided files!

**Comment by sakujo** [comment]
@izzylaif 
this:

> copy to pc and rename one of those files to msgstore.db.crypt12
uninstall whatsapp from the phone
install it again BUT DO NOT RUN IT YET
copy back the renamed file to the whatsapp folder
run the app, confirm the phone number, and agree to restore the database.
Whatsapp might send one of the old keys to your phone to decode the backup

works. TY! (on samsung s4, andr ver 5.0.1, date: 11.01.18)

**Comment by Shabihbhai** [comment]
@andreas-mausch  Please check your email. I sent your one request

**Comment by akkip910** [comment]
Hi
I am using Mi phone with android version 6.0.1 MMB29M.

I have installed all required apps java, whatsapp db extractor tool, whatsapp viewer on my win 10 and usb debugging on. while running extractor tool its not showing backup my data pop up in my phone. And when it completes its not installing whatsapp back to my phone after many attempts also and nothing comes in extracted folder.

Please suggest.

**Comment by akashg079** [comment]
hi i also have this problem i have database backup and key also of that number but still unable to read messages and media using WhatApp viewer can you help me please it's very urgent.... I have everything database and key also but showing  error with unzipping (inflate) in 99%  please help me here 
reply me soon waiting for it ..

**Comment by mariakhan16198** [comment]
i have a problem error with unzipping(inflate). and i m using NSWhatsapp. please resolve it.

**Comment by Juanamary** [comment]
@ andreas-mausch @izzylaif Please if you could help me with the error problem decompress (inflate) by 99% ... I have tried what @izzylaif said but I was not successful, nor do I know if that method was effective ... I do not know how to generate that old key for conversations from a few months ago, or if there is another method to decrypt them ... I have the root phone and the key too but I can only decode the current ones ... I hope to hear from you soon, thanks

**Comment by izzylaif** [comment]
If you have access to the sim card with the phone number, you may try the following.
Do a fresh install of whatsapp but don't open it yet. Copy that old crypt you have to the databases directory (where whatsapp normally stores backup).
Then launch the app, it will prompt for sms verification, after that it may (or may not) ask if you want to restore that database.
That's the only option to try so far.

**Comment by Juanamary** [comment]
Thanks @izzylaif I will try that method to see if it works ... Although I already did it, but I don't remember if I applied it well. I also wanted to know if after 3 years that you have the conversation thread if there would be any effective method for it, but I see that your answer has been like the one you wrote earlier.
Did you or someone really succeed with this method?

**Comment by izzylaif** [comment]
>  And how do I create the database directory before running the app

Sorry, creating folders is basic knowledge. You should really learn how to actually use the devices you spend your entire day with.
This may help though [https://www.youtube.com/watch?v=m13ZuwFvZL4](url)

**Comment by ManasSathyan** [comment]
> > And how do I create the database directory before running the app
> 
> Sorry, creating folders is basic knowledge. You should really learn how to actually use the devices you spend your entire day with.
> This may help though [https://www.youtube.com/watch?v=m13ZuwFvZL4](url)

Oh, I was so stressed out my brain wasn't working properly. And I also got a bit confused with the term database directory. I managed to figure it out tho, and was able to restore what I was looking for. Thank you anyways.
