### ISSUE TITLE
Extracted in txt file there is no phone number

### ISSUE THREAD

**Issue by mbaht** [andreas-mausch/whatsapp-viewer#38]
I have extracted chta history of group..
Is any way to show phone number in txt file?
I need that.. i cant save in html because i have a big history chat.. in txt file contain 2,2 Million row (126 Mb file size)
Pls help me.. Thanks

**Comment by any81** [comment]
Hiii i dont understand ,what you mean about Phone Number?thnx

Il 22 mag 2017 05:39, "mbaht" <notifications@github.com> ha scritto:

**Comment by mbaht** [comment]
Hii... Thanks for reply..

I mean..
If i save in txt file.. there is no Phone number from the sender message.. There is only "he :" and "me :"
How make show the phone number in txt file.. because if i save in html there is phone number like this "xxxx48836231@s.whatsapp.net"

My problem.. icant save in HTML because i have a more 2 million chat.. I have try but allways not responding..

**Comment by andreas-mausch** [comment]
The phone number is printed at the very beginning of the txt file. Maybe you have missed that?
