### ISSUE TITLE
Viewer does not show Images

### ISSUE THREAD

**Issue by wjp79** [andreas-mausch/whatsapp-viewer#42]
Hello...
Last time I opened a msgstore.db in the viewer, I noticed it does no longer show any thumbnails / images  in the chat window. 
All the chats since march 2017 dont have any images.
I'm just curious if I'm  doing something wrong or did something change?

Thank you.

**Comment by luizbossoi** [comment]
Same problem here.. no thumbs

**Comment by utmuk** [comment]
Yep, here too

**Comment by Prabin1985** [comment]
Same here,Need your help ?

**Comment by Nanaki92** [comment]
Same problem here... any solution?

**Comment by andreas-mausch** [comment]
Confirmed, WhatsApp changed their database structure. I need to release a new version. I'm working on it.

**Comment by utmuk** [comment]
Wow, very nice. Is there a compiled executable?

**Comment by andreas-mausch** [comment]
Not yet. I prepare a new release, should be ready within the next couple of days.

**Comment by andreas-mausch** [comment]
v1.10 released.

**Comment by Prabin1985** [comment]
Is the exe file there ?

**Comment by utmuk** [comment]
**Prabin1985**, https://github.com/andreas-mausch/whatsapp-viewer/releases/tag/v1.10
