### ISSUE TITLE
i want to open whatsaap backup database

### ISSUE THREAD

**Issue by rizomz** [andreas-mausch/whatsapp-viewer#43]
i try to open whatsapp backup database but there is message database image disk malformed

**Comment by rizomz** [comment]
i lost my android phone i have got sd card and there is some whatsaap crypt message 
i dont have key i need some information on that messages

**Comment by kiquenet** [comment]
did you get any solution for  your msgstore-2017-MM-dd.X.db.crypt8 files ?

**Comment by andreas-mausch** [comment]
> Can I decrypt the database without the key file?
> WhatsApp is able to do that, but I am not. If you have lost your phone or the key file, the backup is worthless.
> Please, do NOT write me e-mails because you cannot find the key but the messages are SOO important for you. I cannot help you.

http://andreas-mausch.de/whatsapp-viewer/
