### ISSUE TITLE
Runtime Error when trying to decrypt .crypt12 database

### ISSUE THREAD

**Issue by ziyadss** [andreas-mausch/whatsapp-viewer#46]
After I load the database and key files and press OK, I get runtime error, of which a screenshot is attached
![image](https://user-images.githubusercontent.com/17732483/31902594-08550348-b82e-11e7-8f9e-e56ecf2965c1.png)

I tried using another laptop and the same error showed, so it could be related to my own files? I'm not sure & I don't have other files to try.

**Comment by andreas-mausch** [comment]
Uh! Could you provide me sample files to andreas.mausch@gmail.com?

**Comment by ddesario** [comment]
I've used another application to decrypt the file, and the now decrypted .db file actually works with WhatsApp Viewer, so I guess the files weren't corrupted. If the files would still be of use to you, let me know, I'm okay with giving you them if it'd help you for anything.

**Comment by andreas-mausch** [comment]
Yes please, my applications should never crash. :)

**Comment by colgat** [comment]
![failed](https://user-images.githubusercontent.com/33361547/32399019-fc0e9cb4-c103-11e7-8e07-96edf09b53fc.jpg)

доброго дня , что можете сказать , почему так вышло ? тесты на других делал , всё выходило а тут не как а информация очень нужная в файле, возможно помочь ?

**Comment by noise3** [comment]
When I try with small database, the error no appear. With a 200MB database, I get the same error

**Comment by avihaiamar1** [comment]
Hi Andreas, same issue with ~240MB Database.. 

![image](https://user-images.githubusercontent.com/34273714/33608226-959850ec-d9cc-11e7-89ff-73085f79e39b.png)

**Comment by harshadmehta001** [comment]
Hi Buddy,
You have done a great job, I wanted to know if this application has any limitations related to the size of file. It is giving me run time error while decrypting file size of 133 mb.
Thanks

**Comment by andreas-mausch** [comment]
Hi @harshadmehta001, are you willing to share the database? I would take a look at it immediately then.
Currently decryption/uncompressing is done completely in memory, which is probably a bad idea regarding the growing file sizes.

**Comment by dwightyy** [comment]
@andreas-mausch I had the same problem. With me it happens when i go "file > decrypt.crypt12 > input the 2 files", then i recieved this error. I found a workround doing via command line and worked fine with the same 2 files. I gonna try to make a video later if necessary.

**Comment by Khiago** [comment]
Hello @andreas-mausch :)

I got the same Runtime error above with a 400mb Database.
I don't find another way to decrypt it.
Can you help me?
I can send you the files, if you need them

Thanks in advance

**Comment by andreas-mausch** [comment]
@Khiago Yes, please send the files via wetransfer or dropsend to andreas.mausch@gmail.com

Thanks!

**Comment by Khiago** [comment]
Hello @andreas-mausch . Sorry to take long to anwser.
I tried to open my files with "my SQL" and got the same error, so i concluded that my files are corrupted.
I used SQLite to dump to another .db and with the health archive, your software worked great and i was able to read my almost 1gb decrypted database :)

Thanks

**Comment by nico89s** [comment]
I can confirm that runtime error happen when I try to decrypt db.crypt12 larger than 90MB. I try my october 2017 backup with 85MB and 86MB success decrypted. But when I try my December 2017 backup with 96MB file size it start to fail with runtime error message. Of course my newest 144MB database can't decrypted.

**Comment by dc213** [comment]
Hello @andreas-mausch, is it possible to recover deleted messages using whatsapp viewer? If yes, how could I recover them? Thank you.

**Comment by javiersh2000** [comment]
Hi, runtime error in 150 and 200mb any help?
Thank you.

**Comment by andreas-mausch** [comment]
Thanks to whoever gave me the 400mb crypt12 file.
I was able to reproduce the bug finally.

![image](https://user-images.githubusercontent.com/1736847/93713921-53865980-fb5f-11ea-81c0-2be3f029d844.png)

I'm gonna enjoy the rest of the sun for today and come back to this in the evening.

**Comment by andreas-mausch** [comment]
Fixed in v1.13

**Comment by andreas-mausch** [comment]
Sorry for the short delay of three years for such a major bug. 🤦 

Thank you to everyone who sent me test data.

Hope this is now fixed for all possible database files.
