### ISSUE TITLE
Bitdefender antivirus detects virus

### ISSUE THREAD

**Issue by TheDoctor40** [andreas-mausch/whatsapp-viewer#47]
So for some reason my bitdefender antivirus detects Gen:Variant.Johnnie.26779. Virustotal get's some hits with the same results as well. Any explanations why? It would be ashame if I'm not able to safely use this app anymore...

**Comment by andreas-mausch** [comment]
No idea why. I will contact Bitdefender and let you know.

**Comment by TheDoctor40** [comment]
Awesome, thanks! Looking forward to it!

**Comment by andreas-mausch** [comment]
I've submitted the exe as false positive and am waiting for their response. I am very serious about this, I am registered here with my real name and my reputation should not be damaged by this.

Only reason why this might not be a false positive is if my development machine is infected already, but I rather think the AntiVirus heuristics are working a bit too good here.

![screencapture-virustotal-1509566371113](https://user-images.githubusercontent.com/1736847/32295642-2e50ee0e-bf4a-11e7-8ae8-82ac477c6452.png)

**Comment by TheDoctor40** [comment]
That's indeed not so great. I hope the issue get's resolved by the AntiVirus companies fast!

**Comment by andreas-mausch** [comment]
Ok, so WhatsApp Viewer is now "clean" for BitDefender. It still has 5 hits at virustotal.com, I will check if I can contact the vendors. I close this.
