### ISSUE TITLE
fails to open crypt12 files by throwing runtime error

### ISSUE THREAD

**Issue by pvkiranatgithub** [andreas-mausch/whatsapp-viewer#59]
please find the screenshot attached. WhatsApp viewer throws the attached error and dies.
please help
![image](https://user-images.githubusercontent.com/35039474/34493099-5ef40d24-f010-11e7-8a4c-e9870d24a0fa.png)

**Comment by pvkiranatgithub** [comment]
please let us know, if the key file changes, every time when a backup gets created.

**Comment by dwightyy** [comment]
@pvkiranatgithub  try to do it via command line

**Comment by tayanov** [comment]
+1, db over 350 mb not view, but another db 150 mb work perf.

**Comment by jialongz2** [comment]
How to run db file over the size limit

**Comment by mahmudayaz** [comment]
Any update? i am facing the same issue.

**Comment by almerindo** [comment]
Any Update?
For more informations:
![error01](https://user-images.githubusercontent.com/554495/51802749-ac3b0d00-222b-11e9-825b-01d382fd4710.PNG)

And.. yes, the size of database > 350Mb

Thanks

**Comment by Anpix** [comment]
Same problem here.
My database file size is just 279 MB

Note: Using the app Whatcrypt in my android device, the database was decripted successfully.

**Comment by andreas-mausch** [comment]
Duplicate of #46
