### ISSUE TITLE
Can't add my key file

### ISSUE THREAD

**Issue by Zephyrv** [andreas-mausch/whatsapp-viewer#6]
I extracted my key using a non rooted method, and I've got it in a folder on my PC. However, when I browse into that folder through the program, it doesn't see any files in there that it can use.

**Comment by andreas-mausch** [comment]
The Viewer filters for the exact filename "key". If your key file has a different name it doesn't show up in the program.

**Comment by Zephyrv** [comment]
Thanks for the reply. The keyfile I have still isn't working, but using the latest version and using the wa.db together with the msgstore.db works just great. Keep up the great work! 

     On Monday, 19 January 2015, 17:48, Andreas Mausch <notifications@github.com> wrote:
   

 The Viewer filters for the exact filename "key". If your key file has a different name it doesn't show up in the program.—
