### ISSUE TITLE
Text below images is missing

### ISSUE THREAD

**Issue by tomuc** [andreas-mausch/whatsapp-viewer#60]
The Text below images is not shown.

**Comment by Invictaz** [comment]
Not sure if this is separate text because in Whatsapp Android you can forward an image, but the text that is under it is not forwarded.

**Comment by andreas-mausch** [comment]
messages.media_caption

**Comment by Invictaz** [comment]
@andreas-mausch Can you build it please?

**Comment by andreas-mausch** [comment]
We'd be faster if you'd help me. ;)
