### ISSUE TITLE
Can this be compiled on linux?

### ISSUE THREAD

**Issue by rudolfbyker** [andreas-mausch/whatsapp-viewer#66]
Can this project be compiled on Linux, or do you only target Windows? If so, would you show the basic steps, or provide a Makefile?

(I tried running the released .exe in wine, and it shows the contacts, but not the messages.)

**Comment by andreas-mausch** [comment]
No, WhatsApp Viewer can't be compiled on Linux. I use Win32 API for the GUI. I'd like to use an platform independent GUI framework, but I dislike all I know. :(

For me WhatsApp Viewer runs perfectly fine on wine. Can you share a screenshot how it looks like?

I've experimented with Electron in this branch: https://github.com/andreas-mausch/whatsapp-viewer/tree/electron
This one builds on Linux. However, I disliked the 150mb executable and didn't continue there.
