### ISSUE TITLE
How to Open whatsapp-viewer

### ISSUE THREAD

**Issue by naumanafsar** [andreas-mausch/whatsapp-viewer#76]
Hello Sir!
I am a Linux user (Almost NO Experience on Windows), i just downloaded the source file but i don't know how to start the application as there's no .exe file!
And you've used <windows.h> library so i can't build it on Linux either.

Can you please tell me how do i open the application?

**Comment by andreas-mausch** [comment]
Hi there,
You can find the .exe file here: https://github.com/andreas-mausch/whatsapp-viewer/releases/download/v1.12/WhatsApp.Viewer.zip

It should run without problems in wine.
(I am almost exclusively on Linux, too.)

**Comment by naumanafsar** [comment]
Thank you!
It is running flawlessly on Wine :)
