### ISSUE TITLE
You can extract Messages.db with your program?

### ISSUE THREAD

**Issue by LukeDaniel16** [andreas-mausch/whatsapp-viewer#89]
Hey, i have the old's files from my old Windows Phone (Lumia 535), and i have the folder from the Whatsapp backup, but, the archives that has in the folders are "Messages.db, calls.db and Settings.db", how you can see, the archives are different than Android or iOs file backup, not are "Crypt12..." in the end of name file, i tried to open the Messages.db with your software but the program return to me an error.
You can help me? :/

**Comment by billyproud** [comment]
![WhatsApp-chatt med مدرسة المشاغبين🤣 - Google (2)](https://user-images.githubusercontent.com/32924967/58795830-f9752400-85fb-11e9-88d5-09ea723ecdda.png)
![WhatsApp-chatt med مدرسة المشاغبين🤣 - Google (3)](https://user-images.githubusercontent.com/32924967/58795833-fb3ee780-85fb-11e9-88b2-2aadea2d2291.png)
[WhatsApp-chatt med مدرسة المشاغبين🤣.txt](https://github.com/andreas-mausch/whatsapp-viewer/files/3247097/WhatsApp-chatt.med.txt)
[WhatsApp-chatt med مدرسة المشاغبين🤣.txt](https://github.com/andreas-mausch/whatsapp-RSAviewer/files/3247098/WhatsApp-chatt.med.txt)
[WhatsApp-chatt med مدرسة المشاغبين🤣.txt](https://github.com/andreas-mausch/whatsapp-viewer/files/3247100/WhatsApp-chatt.med.txt)

**Comment by RAIMUNDOS54** [comment]
How did you do it? Could you please help? Thank you in advance.

> ![WhatsApp-chatt med مدرسة المشاغبين🤣 - Google (2)](https://user-images.githubusercontent.com/32924967/58795830-f9752400-85fb-11e9-88d5-09ea723ecdda.png)
> ![WhatsApp-chatt med مدرسة المشاغبين🤣 - Google (3)](https://user-images.githubusercontent.com/32924967/58795833-fb3ee780-85fb-11e9-88b2-2aadea2d2291.png)
> [WhatsApp-chatt med مدرسة المشاغبين🤣.txt](https://github.com/andreas-mausch/whatsapp-viewer/files/3247097/WhatsApp-chatt.med.txt)
> [WhatsApp-chatt med مدرسة المشاغبين🤣.txt](https://github.com/andreas-mausch/whatsapp-RSAviewer/files/3247098/WhatsApp-chatt.med.txt)
> [WhatsApp-chatt med مدرسة المشاغبين🤣.txt](https://github.com/andreas-mausch/whatsapp-viewer/files/3247100/WhatsApp-chatt.med.txt)

**Comment by andreas-mausch** [comment]
Windows Phone is not supported.
