### ISSUE TITLE
Export functions

### ISSUE THREAD

**Issue by rcolaianni** [andreas-mausch/whatsapp-viewer#9]
It's a great tool, my compliments.
There is one problem, in the export .html mode there aren't timestamps and in the export .txt there aren't images.
The best view is in the tool but it's not possibile to import in another document.
Thank you.

**Comment by andreas-mausch** [comment]
Will be in v1.8

**Comment by rcolaianni** [comment]
Thank you very much.

**Comment by btwael** [comment]
@andreas-mausch great project, I hope exporting functions will support JSON format :+1:

**Comment by WACRYP** [comment]
Great tool and works verry good until.... Whatsapp updated... so when can we aspect a update to decrypt this (new) version db? seems that the key is the same but it gives error "could not decrypt block"...
Thank you!
