### ISSUE TITLE
whatsapp viewer 1.12

### ISSUE THREAD

**Issue by Vcald** [andreas-mausch/whatsapp-viewer#90]
I downloaded the last version from github...
I opened the .crypt12 file...I opened the key (my phone is rooted)...and then tried to decrypt it...after a few seconds the program simply closes...and no output written...
The database is 170 Mb...can this be the problem?

**Comment by 123456120** [comment]
Dear sir please send whatsapp viewer software please help.

**Comment by andreas-mausch** [comment]
Most likely a duplicate of #46
