### ISSUE TITLE
SQL Instruction?

### ISSUE THREAD

**Issue by joaoguariglia** [andreas-mausch/whatsapp-viewer#97]
I would like to know how you called the msgstore database filters containing and concatenating only the number sent or received and the message, because when I enter the database with the DB Browser tool it is a mess, what would be the SQL statement to appear only the user who sent or received the message and the message as you did in your program?

**Comment by andreas-mausch** [comment]
You can find the queries here:

https://github.com/andreas-mausch/whatsapp-viewer/blob/2b4e727dfba3ad7847a13588854364ca97e4725b/source/WhatsApp/Database.cpp
