### ISSUE TITLE
Runtime Error!

### ISSUE THREAD

**Issue by sergio-custodio** [andreas-mausch/whatsapp-viewer#99]
When trying to decrypt my db, message box:
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Runtime Error!

Program: C:\Users\sergi\Desktop\WhatsApp Viewer.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by sergio-custodio** [comment]
I can send DB and key if necessary.

**Comment by andreas-mausch** [comment]
Sorry!

Yes, your files would help. Please upload them somewhere (please encrypt them / use a password) and send a link and password to andreas.mausch@gmail.com.

How much RAM do you have? Decryption is done completely in memory and it uses a lot..

**Comment by sergio-custodio** [comment]
Thanks! I've shared db and key files with google drive directly to your gmail. 

I have 16GB of RAM, usually having half of it free. WhatsApp Viewer seems to use about 1GB to try to processes my 400MB db before it crashes, so I don't think that's an issue.

**Comment by andreas-mausch** [comment]
Thanks for the additional info. :+1:
I've received the file, feel free to delete it from the cloud.

I don't have a development environment set up right now, so it might need a fews days.

However runtime errors should never happen, so I'm again very sorry about this and try to fixing this asap.

**Comment by Paskal-MY** [comment]
I'm having this issue too.
my crypt12 file is around 1gb in size. my pc is win10 64bit, with 8gb ram.

**Comment by javiersh2000** [comment]
I have the same problem but with a 220 mb file, any help?

**Comment by erickamoedo** [comment]
![errorr](https://user-images.githubusercontent.com/8376149/85367063-e54dde80-b4fe-11ea-9758-d2531b706279.jpg)


I have the same problem  :/

8 ram / i7

Do you have any suggestion for me?

**Comment by danielporto** [comment]
I also got the same issue.
Windows 10, 64. vm from https://app.vagrantup.com/YuvrajTakey/boxes/Windows
any hints or workaround??

**Comment by andreas-mausch** [comment]
Sorry I haven't fixed it yet. :(
I can't even excuse it by a lack of time (because I have plenty right now), but just too many other things I like to do.

I try to fix it next week, meanwhile the **workaround** is to decrypt the file via node.js, java or python:

- JS: https://github.com/andreas-mausch/whatsapp-viewer/blob/ddb059d02dbe544cd8163561eb7a918192c17348/decrypt-crypt12.js
- Python and Java: https://github.com/EliteAndroidApps/WhatsApp-Crypt12-Decrypter

**Comment by andreas-mausch** [comment]
Related to #37 #46 #59 #93

**Comment by Davidorum** [comment]
Hello guys, Andreas,

I had the same issue trying to uncrypt the DB (150Mb). A workaround valid for me was to launch via command line, like this:

    _"WhatsApp Viewer.exe" -decrypt12 msgstore.db.crypt12 key msgstore.db_

Hope can help! :)

**Comment by dghl08** [comment]
> Sorry I haven't fixed it yet. :(
> I can't even excuse it by a lack of time (because I have plenty right now), but just too many other things I like to do.
> 
> I try to fix it next week, meanwhile the **workaround** is to decrypt the file via node.js, java or python:
> 
> * JS: https://github.com/andreas-mausch/whatsapp-viewer/blob/ddb059d02dbe544cd8163561eb7a918192c17348/decrypt-crypt12.js
> * Python and Java: https://github.com/EliteAndroidApps/WhatsApp-Crypt12-Decrypter

for files showing runtime error 
use link provided below in safeboot mode
Python and Java: https://github.com/EliteAndroidApps/WhatsApp-Crypt12-Decrypter

**Comment by andreas-mausch** [comment]
Let's continue here: #46
